### ISSUE TITLE
Do not support the "|" operator

### ISSUE THREAD

**Issue by iwctwbai** [timescale/promscale#540] opened 2021-03-19 13:34 UTC
```
ifHCInOctets{instance="0.0.0.0|121.31.23.11"}
```
**No data returned**

```
ifHCInOctets{instance="0.0.0.0"}
```
Return the data
```
ifHCInOctets{instance="121.31.23.11"}
```
Return the data

**Comment by Harkishen-Singh** [comment] 2021-03-22 16:26
@iwctwbai I don't think that's any unintentional behaviour. If you want to use a pipe, then it should be a regex expression.

Like: `ifHCInOctets{instance=~"0.0.0.0|121.31.23.11}`

**Comment by iwctwbai** [comment] 2021-03-24 01:58
This was not detected in the 100% compatibility test, but promQL is supported
You said this I remember testing is also not good
Now I'm using this scheme
```
ifHCInOctets{instance=~"^0.0.0.0$|^121.31.23.11$"}
```
It looks tedious

**Comment by Harkishen-Singh** [comment] 2021-03-24 02:37
@iwctwbai sorry, I do not understand here. Is the behaviour of PromQL evaluation something different than that of Prometheus's PromQL engine?

**Comment by iwctwbai** [comment] 2021-03-24 06:45
@Harkishen-Singh 
Maybe I'm not making myself clear
Prometheus's PromQL engine can parse ''' ifHCInOctets{instance="0.0.0.0|121.31.23.11"} ''' , but promscale is not.

**Comment by iwctwbai** [comment] 2021-03-24 06:49
I got around this problem with regular expressions（''' ifHCInOctets{instance=~"^0.0.0.0$|^121.31.23.11$"}  '''）, but it's obviously not a good solution

**Comment by Harkishen-Singh** [comment] 2021-03-24 07:02
@iwctwbai 
I tried parsing ` ifHCInOctets{instance="0.0.0.0|121.31.23.11"}` on Promscale's latest master commit and its showing me no errors. The same is true for Prometheus. Can you please tell your Promscale version (also Prometheus for better info)? Maybe this was some previous issue that was later fixed.

**Comment by Harkishen-Singh** [comment] 2021-03-24 07:04
Ah, i see that you are able to parse as well, its that the data is not being returned. Can you tell me which exporter is this so that I can replicate this issue on my side?

**Comment by iwctwbai** [comment] 2021-03-25 02:24
@Harkishen-Singh 
https://github.com/prometheus/snmp_exporter
Thank you very much

**Comment by Harkishen-Singh** [comment] 2021-03-30 08:53
@iwctwbai I tried reproducing this issue, by creating a new metric that has a `|` in the label value and then querying as normal equal matcher with the pipe. It works for me as I get the results with the pipe as well, even though the matcher is just EQL. So this means I am unable to reproduce this issue.

Can you tell me which Promscale version are you using?

**Comment by iwctwbai** [comment] 2021-03-30 11:41
version：0.21
This is weird because I'm doing it through regular expressions right now
@Harkishen-Singh

**Comment by iwctwbai** [comment] 2021-03-31 18:41
it's a query-time thing to search for either value @cevian

**Comment by Harkishen-Singh** [comment] 2021-04-07 14:02
@iwctwbai the pipe will work only if you have a regex operator match. If you want the pipe to work without the regex, (in a EQL operator `=`) then the actual label value should have the pipe. 

To confirm this, you can see the actual behaviour of prometheus at https://demo.promlens.com/

`go_goroutines{job="cadvisor|prometheus"}` gives empty result, but `go_goroutines{job=~"cadvisor|prometheus"}` gives you both series, one for cadvior and other for prometheus.

**Comment by cevian** [comment] 2021-07-09 20:34
I am closing the issue because I think it's resolved? But feel free to reopen if it is not

**Closed by cevian** 2021-07-09 20:34 UTC
