### ISSUE TITLE
Promscale fails to run after restart

### ISSUE THREAD

**Issue by allgreed** [timescale/promscale#285] opened 2020-10-05 21:58 UTC
I'm running promscale on Digitalocean inside a k8s deployment with a managed postgres db. When I kill the initial working pod and pods created after that terminate with an error and display following log:
```
level=info ts=2020-10-05T21:54:14.159Z caller=log.go:76 msg="Version:0.1.0-beta.5; Commit Hash: "
level=info ts=2020-10-05T21:54:14.159Z caller=log.go:76 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:private-main-sql-do-user-3848532-0.b.db.ondigitalocean.com Port:25060 User:doadmin Password:[redacted] Database:timescale SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:false PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$}"
level=warn ts=2020-10-05T21:54:14.255Z caller=log.go:81 msg="the promscale extension is not available, proceeding without extension"
level=warn ts=2020-10-05T21:54:14.262Z caller=log.go:81 msg="No adapter leader election. Group lock id is not set. Possible duplicate write load if running multiple connectors"
level=info ts=2020-10-05T21:54:14.320Z caller=log.go:76 msg="host=private-main-sql-do-user-3848532-0.b.db.ondigitalocean.com port=25060 user=doadmin dbname=timescale password='****' sslmode=require connect_timeout=10" numCopiers=4 pool_max_conns=40 pool_min_conns=1
level=error ts=2020-10-05T21:54:14.340Z caller=log.go:86 errstartingingestor="ERROR: functionality not supported under the current license \"ApacheOnly\", license (SQLSTATE 0A000)"
level=error ts=2020-10-05T21:54:14.341Z caller=log.go:86 msg="aborting startup due to error" err="client creation error: ERROR: functionality not supported under the current license \"ApacheOnly\", license (SQLSTATE 0A000)"
```

**Comment by Harkishen-Singh** [comment] 2020-10-05 22:13
This is a duplicate of https://github.com/timescale/promscale/issues/150. We are working on this and the fix will be out soon. TSL version of Timescaledb should not cause only issue (assuming compression is the problem, as in case of the mentioned issue)

**Comment by allgreed** [comment] 2020-10-05 23:10
@Harkishen-Singh no idea how to debug it, so I'm agnostic about your assumption. Yet the behaviour is weird as until the first restart everything works great. And it seems to be tied to the database as when I recreate it and restart promscale everything works great again. Does that description match the compression thingy in your opinion?

**Comment by Harkishen-Singh** [comment] 2020-10-06 04:03
What do you mean "when I recreate it"?

**Comment by allgreed** [comment] 2020-10-06 21:30
Sorry, bad wording choice. By recreate I mean: delete the database and spin up a new empty one with the same name

**Comment by cevian** [comment] 2020-10-08 22:11
#291 should fix this issue. But be warned the ApacheOnly version of Timescale will not have compression.

**Comment by antekresic** [comment] 2020-10-13 12:29
With #291 merged in, this issue should be resolved.

Feel free to reopen it if you continue to get this issue with the latest build.

**Closed by antekresic** 2020-10-13 12:29 UTC
