### ISSUE TITLE
`-flag true` prevents other flags from being set

### ISSUE THREAD

**Issue by 0x4A6F** [timescale/promscale#290] opened 2020-10-06 17:28 UTC
During development of a [module and tests for NixOS](https://github.com/NixOS/nixpkgs/pull/97372), I stumbled upon this behavior.

```
postgresql_11 # [  200.961803] promscale[897]: level=info ts=2020-10-06T17:10:05.821Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: 0.1.0"
postgresql_11 # [  201.014101] promscale[897]: level=info ts=2020-10-06T17:10:05.910Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:postgres Password: Database:timescale SslMode:require DbConnectRetries:0 AsyncAcks:true ReportInterval:0 LabelsCacheSize:1234 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:1 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
postgresql_11 # [  201.491231] promscale[897]: level=error ts=2020-10-06T17:10:06.388Z caller=runner.go:110 msg="aborting startup due to error" err="failed to connect to `host=localhost user=postgres database=timescale`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"
postgresql_11 # [  201.551692] systemd[1]: timescale-prometheus.service: Main process exited, code=exited, status=1/FAILURE
postgresql_11 # [  201.574625] systemd[1]: timescale-prometheus.service: Failed with result 'exit-code'.
postgresql_11 # [  201.598685] systemd[1]: timescale-prometheus.service: Consumed 3.118s CPU time, received 100B IP traffic, sent 140B IP traffic.
```

If environment variables are set, promscale works.
```
postgresql_11 # [  211.911804] promscale[898]: level=info ts=2020-10-06T17:02:05.870Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: 0.1.0"
postgresql_11 # [  211.944689] promscale[898]: level=info ts=2020-10-06T17:02:05.928Z caller=runner.go:104 config="&{ListenAddr:[::1]:9202 TelemetryPath:/metric PgmodelCfg:{Host:::1 Port:5433 User:postgres Password: Database:timescaledb SslMode:prefer DbConnectRetries:23 AsyncAcks:true ReportInterval:3456 LabelsCacheSize:1234 MetricsCacheSize:2345 SeriesCacheSize:0 WriteConnectionsPerProc:1 MaxConnections:-1} LogCfg:{Level:info Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
postgresql_11 # [  224.009903] prometheus[899]: level=info ts=2020-10-06T17:02:17.980Z caller=main.go:308 msg="No time or size retention was set so using the default time retention" duration=15d
postgresql_11 # [  224.040902] prometheus[899]: level=info ts=2020-10-06T17:02:18.033Z caller=main.go:343 msg="Starting Prometheus" version="(version=, branch=, revision=)"
postgresql_11 # [  224.057500] prometheus[899]: level=info ts=2020-10-06T17:02:18.051Z caller=main.go:344 build_context="(go=go1.14.8, user=, date=)"
postgresql_11 # [  224.083290] prometheus[899]: level=info ts=2020-10-06T17:02:18.076Z caller=main.go:345 host_details="(Linux 5.4.63 #1-NixOS SMP Sat Sep 5 09:22:51 UTC 2020 x86_64 postgresql11 (none))"
postgresql_11 # [  224.101096] prometheus[899]: level=info ts=2020-10-06T17:02:18.094Z caller=main.go:346 fd_limits="(soft=1024, hard=524288)"
postgresql_11 # [  224.120293] prometheus[899]: level=info ts=2020-10-06T17:02:18.113Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
postgresql_11 # [  224.339007] prometheus[899]: level=info ts=2020-10-06T17:02:18.337Z caller=main.go:684 msg="Starting TSDB ..."
postgresql_11 # [  224.377796] prometheus[899]: level=info ts=2020-10-06T17:02:18.375Z caller=web.go:524 component=web msg="Start listening for connections" address=127.0.0.1:9090
postgresql_11 # [  225.122602] prometheus[899]: level=info ts=2020-10-06T17:02:19.098Z caller=head.go:641 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
postgresql_11 # [  225.141040] prometheus[899]: level=info ts=2020-10-06T17:02:19.120Z caller=head.go:655 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=569.905µs
postgresql_11 # [  225.159558] prometheus[899]: level=info ts=2020-10-06T17:02:19.130Z caller=head.go:661 component=tsdb msg="Replaying WAL, this may take a while"
postgresql_11 # [  225.225935] prometheus[899]: level=info ts=2020-10-06T17:02:19.224Z caller=head.go:713 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
postgresql_11 # [  225.232917] prometheus[899]: level=info ts=2020-10-06T17:02:19.231Z caller=head.go:716 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=6.952839ms wal_replay_duration=88.093598ms total_replay_duration=117.540358ms
postgresql_11 # [  225.310008] prometheus[899]: level=info ts=2020-10-06T17:02:19.308Z caller=main.go:700 fs_type=EXT4_SUPER_MAGIC
postgresql_11 # [  225.323604] prometheus[899]: level=info ts=2020-10-06T17:02:19.321Z caller=main.go:701 msg="TSDB started"
postgresql_11 # [  225.342721] prometheus[899]: level=info ts=2020-10-06T17:02:19.341Z caller=main.go:805 msg="Loading configuration file" filename=/nix/store/4ajdhjh27qmv9iiigx4mm64k5b4dg028-prometheus.yml-checkconfig-checked
postgresql_11 # [  225.455925] prometheus[899]: ts=2020-10-06T17:02:19.454Z caller=dedupe.go:112 component=remote level=info remote_name=d159e8 url=http://[::1]:9202/write msg="Starting WAL watcher" queue=d159e8
postgresql_11 # [  225.506823] prometheus[899]: ts=2020-10-06T17:02:19.505Z caller=dedupe.go:112 component=remote level=info remote_name=d159e8 url=http://[::1]:9202/write msg="Replaying WAL" queue=d159e8
postgresql_11 # [  226.128545] prometheus[899]: level=info ts=2020-10-06T17:02:20.107Z caller=main.go:833 msg="Completed loading of configuration file" filename=/nix/store/4ajdhjh27qmv9iiigx4mm64k5b4dg028-prometheus.yml-checkconfig-checked
postgresql_11 # [  226.162256] prometheus[899]: level=info ts=2020-10-06T17:02:20.160Z caller=main.go:652 msg="Server is ready to receive web requests."
postgresql_11 # [  227.275711] postgres[913]: [913] WARNING:
postgresql_11 # [  227.278548] postgres[913]:   WELCOME TO
postgresql_11 # [  227.284635] postgres[913]:    _____ _                               _     ____________
postgresql_11 # [  227.292924] postgres[913]:   |_   _(_)                             | |    |  _  \ ___ \
postgresql_11 # [  227.302005] postgres[913]:     | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
postgresql_11 # [  227.306920] postgres[913]:     | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
postgresql_11 # [  227.316598] postgres[913]:     | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
postgresql_11 # [  227.328431] postgres[913]:     |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
postgresql_11 # [  227.336612] postgres[913]:                  Running version 1.7.4
postgresql_11 # [  227.341796] postgres[913]:   For more information on TimescaleDB, please visit the following links:
postgresql_11 # [  227.347543] postgres[913]:
postgresql_11 # [  227.353955] postgres[913]:    1. Getting started: https://docs.timescale.com/getting-started
postgresql_11 # [  227.359387] postgres[913]:    2. API reference documentation: https://docs.timescale.com/api
postgresql_11 # [  227.364647] postgres[913]:    3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture
postgresql_11 # [  227.371862] postgres[913]:
postgresql_11 # [  227.375873] postgres[913]:   Note: Please enable telemetry to help us improve our product by running: ALTER DATABASE "timescaledb" SET timescaledb.telemetry_level = 'basic';
postgresql_11 # [  227.382503] postgres[913]:
postgresql_11 # [  227.386597] postgres[913]: [913] CONTEXT:  PL/pgSQL function inline_code_block line 23 at RAISE
postgresql_11 # [  232.437994] promscale[898]: level=warn ts=2020-10-06T17:02:26.418Z caller=migrate.go:128 msg="could not install promscale: the extension is not available. continuing without extension"
postgresql_11 # [  233.455826] promscale[898]: level=info ts=2020-10-06T17:02:27.439Z caller=client.go:90 msg="host=::1 port=5433 user=postgres dbname=timescaledb password='' sslmode=prefer connect_timeout=10" numCopiers=1 pool_max_conns=50 pool_min_conns=1
postgresql_11 # [  233.530939] promscale[898]: level=info ts=2020-10-06T17:02:27.529Z caller=sql_ingest.go:82 msg="outputting throughpput info once every 3456s"
postgresql_11 # [  233.928745] promscale[898]: level=info ts=2020-10-06T17:02:27.927Z caller=runner.go:123 msg="Starting up..."
postgresql_11 # [  233.948380] promscale[898]: level=info ts=2020-10-06T17:02:27.944Z caller=runner.go:124 msg=Listening addr=[::1]:9202
postgresql_11 # Connection to localhost (::1) 9202 port [tcp/wap-wsp-s] succeeded!
(239.71 seconds)
postgresql_11: must fail: ps auxwww | grep snakeOilPassword | grep -v grep
(1.18 seconds)
postgresql_11: must succeed: curl -s --fail http://[::1]:9202/metric | grep -qi go_gc_duration_seconds
(0.98 seconds)
(241.86 seconds)
(242.02 seconds)
test script finished in 242.27s
cleaning up
killing postgresql_11 (pid 6)
(0.00 seconds)
copying 1 paths...
copying path '/nix/store/k6qmg5gldvp9b54zxc184rzm9hsrvpvm-vm-test-run-timescale-prometheus' from 'ssh://build@buildhost...
/nix/store/k6qmg5gldvp9b54zxc184rzm9hsrvpvm-vm-test-run-timescale-prometheus
```

**Comment by Harkishen-Singh** [comment] 2020-10-06 17:46
> If environment variables are set, promscale works

Could you detail on this?

**Comment by 0x4A6F** [comment] 2020-10-06 18:08
I'm setting the environment variables, if `RestElection:true` in `nixos/modules/services/monitoring/promscale.nix`.

```
      environment = mkIf cfg.leaderElection.rest {
        TS_PROM_ASYNC_ACKS = boolToString cfg.asyncAcks;
        TS_PROM_DB_CONNECT_RETRIES = toString cfg.database.connectRetries;
        TS_PROM_DB_HOST = cfg.database.host;
        TS_PROM_DB_NAME = cfg.database.name;
        TS_PROM_DB_PORT = toString cfg.database.port;
        TS_PROM_DB_SSL_MODE = cfg.database.sslMode;
        TS_PROM_DB_USER = cfg.database.user;
        TS_PROM_LABELS_CACHE_SIZE = toString cfg.labelsCacheSize;
        TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_ID = toString cfg.leaderElection.pg.advisoryLockId;
        TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_PROMETHEUS_TIMEOUT = cfg.leaderElection.pg.advisoryLockPrometheusTimeout;
        TS_PROM_LEADER_ELECTION_REST = toString cfg.leaderElection.rest;
        TS_PROM_LOG_LEVEL = cfg.logLevel;
        TS_PROM_METRICS_CACHE_SIZE = toString cfg.metricsCacheSize;
        TS_PROM_MIGRATE = cfg.migrate;
        TS_PROM_SCHEDULED_ELECTION_INTERVAL = cfg.leaderElection.scheduledElectionInterval;
        TS_PROM_TPUT_REPORT = toString cfg.tputReport;
        TS_PROM_WEB_LISTEN_ADDRESS = "${cfg.web.listenAddress}:${toString cfg.web.listenPort}";
        TS_PROM_WEB_TELEMETRY_PATH = cfg.web.telemetryPath;
      };
```

This leads to promscale starting with non-default settings defined in `nixos/tests/promscale.nix`.
Settings are also applied through command line args, if `RestElection:false`.

Setting these variables through command line args (previous block commented out), while `RestElection:true` uses default values and errors out trying to connect to postgres.

**Comment by JLockerman** [comment] 2020-10-07 19:44
on my local machine
both
```bash
> TS_PROM_DB_HOST=foo go run ./cmd/promscale  -db-user mat -db-password password -db-name mat -leader-election-rest true
level=info ts=2020-10-07T19:40:17.625Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T19:40:17.625Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:foo Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
and
```bash
> TS_PROM_LEADER_ELECTION_REST=true TS_PROM_DB_HOST=foo go run ./cmd/promscale  -db-user mat -db-password password -db-name mat
level=info ts=2020-10-07T19:40:56.791Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T19:40:56.791Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:foo Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
have the correct config options, which makes me think it's not `RestElection` per sei that's causing the issue...

**Comment by JLockerman** [comment] 2020-10-07 19:51
@0x4A6F do you have the command-string and environment variables that are used in the erroneous case?

**Comment by 0x4A6F** [comment] 2020-10-07 19:51
There are no environment variables set in the erroneous case. Have you tried to set TS_PROM_DB_HOST only through command line args?

**Comment by JLockerman** [comment] 2020-10-07 19:54
@0x4A6F yup, still gives me the same configuration
```bash
> TS_PROM_LEADER_ELECTION_REST=true go run ./cmd/promscale  -db-user mat -db-password password -db-name mat -db-host foo
level=info ts=2020-10-07T19:53:46.445Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T19:53:46.445Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:foo Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```

**Comment by JLockerman** [comment] 2020-10-07 20:02
@0x4A6F  aha!
```bash
> go run ./cmd/promscale -leader-election-rest true  -db-user mat -db-password password -db-name mat -async-acks  -db-host foo
level=info ts=2020-10-07T19:59:33.913Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T19:59:33.913Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:postgres Password: Database:timescale SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
notably, if we use `-leader-election-rest` instead of `-leader-election-rest true` the issue does not occur
```bash
> go run ./cmd/promscale -leader-election-rest  -db-user mat -db-password password -db-name mat -async-acks  -db-host foo
level=info ts=2020-10-07T20:00:22.395Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T20:00:22.395Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:foo Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:true ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
and it only invalidates the flags after the leader election one
```bash
> go run ./cmd/promscale -db-user mat -db-password password -db-name mat -leader-election-rest true -async-acks  -db-host foo
level=info ts=2020-10-07T20:01:46.226Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T20:01:46.227Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
we must be gobbling arguments to eagerly...

**Comment by JLockerman** [comment] 2020-10-07 20:06
it happens with other boolean flags as well
```bash
> go run ./cmd/promscale -db-user mat -db-password password -db-name mat -leader-election-rest -async-acks true  -db-host foo
level=info ts=2020-10-07T20:04:35.929Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T20:04:35.929Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:true ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
using `-flag=true` does not cause the issue
```bash
go run ./cmd/promscale -db-user mat -db-password password -db-name mat -leader-election-rest -async-acks=true -db-host foo
level=info ts=2020-10-07T20:05:49.511Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T20:05:49.511Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:foo Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:true ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```

**Comment by JLockerman** [comment] 2020-10-07 20:08
replacing `true` with another string also causes the issue.
```bash
> go run ./cmd/promscale -db-user mat -db-password password -db-name mat -leader-election-rest -async-acks bar -db-host foo
level=info ts=2020-10-07T20:07:00.279Z caller=runner.go:103 msg="Version:0.1.0; Commit Hash: "
level=info ts=2020-10-07T20:07:00.279Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:mat Password:password Database:mat SslMode:require DbConnectRetries:0 AsyncAcks:true ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:true PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"
```
my current guess is that `-flag <bool>` is not supported by go's flag package, instead treating the string after the flag as the first positional argument

**Comment by JLockerman** [comment] 2020-10-07 20:11
[from the docs](https://golang.org/pkg/flag/)

> The following forms are permitted:
> 
> ```
> -flag
> -flag=x
> -flag x  // non-boolean flags only
> ```
> One or two minus signs may be used; they are equivalent. The last form is not permitted for boolean flags because the meaning of the command
> 
> `cmd -x *`
> where * is a Unix shell wildcard, will change if there is a file called 0, false, etc. You must use the -flag=false form to turn off a boolean flag.
> 
> Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".

**Comment by 0x4A6F** [comment] 2020-10-07 20:13
Thanks.

**Comment by JLockerman** [comment] 2020-10-07 22:36
since this is apparently not a bug, I'm renaming the issue to make it easier for future searches, and closing.

**Closed by JLockerman** 2020-10-07 22:36 UTC
