### ISSUE TITLE
Remote read with high-availability enabled

### ISSUE THREAD

**Issue by aburkevics** [timescale/promscale#597] opened 2021-04-21 09:25 UTC
Hello!
I'm trying to configure Prometheus high-availability setup with Promscale using the new setup described here - https://github.com/timescale/promscale/blob/master/docs/high-avaliability/prometheus-HA.md

I'm having an issue that when Promscale is started with `-enable-ha=true` flag, Prometheus doesn't seem to fetch the data from "remote_read" after re-deployment.

This is the related configuration in Prometheus that I use.
external labels:
```
  external_labels:
    __replica__: ha-prometheus-server-0
    cluster: ha-prometheus-poc
```
write:
```
remote_write:
- queue_config:
    batch_send_deadline: 10s
    capacity: 10000
    max_backoff: 10s
    max_samples_per_send: 3000
    max_shards: 200
    min_backoff: 100ms
    min_shards: 4
  remote_timeout: 30s
  url: http://promscale-connector:9201/write
```
read:
```
remote_read:
- read_recent: true
  url: http://promscale-connector:9201/read
```

For reference, I'm running Timescaledb docker image `timescale/timescaledb:2.2.0-pg12` & Promscale in kubernetes with image - `timescale/promscale:0.3.0`.

Currently for simplicity I'm running single nodes of Prometheus, Promscale & TimescaleDB.

I would expect that while Promscale & TimescaleDB are running and data is retained, I can wipe my Prometheus instance, bring it back up with the same config and it will read the historical data via Promscale. That is what I've tested without `-enable-ha=true` in Promscale and it was working.

If I had deployed promscale without HA before and later deploy it with it, then Prometheus will successfully read the metrics from before HA was enabled.

I see that Promscale is writing data to TimescaleDB when HA is enabled:
`level=info ts=2021-04-21T09:22:36.577Z caller=write.go:96 msg="Samples write throughput" samples/sec=12000`

Is there a way we should tell the Promscale read API to fetch metrics for specific `cluster` value?

**Comment by VineethReddy02** [comment] 2021-04-21 10:09
Hi!

So the samples ingested into Promscale will hold distinct label sets for different Prometheus clusters i.e. `cluster: <clustername>` so querying with cluster label set should let you query data specific to Prometheus cluster from Promscale.

**Comment by aburkevics** [comment] 2021-04-21 10:14
Hi!
Do you mean adding something like this to remote_read config?
```
     required_matchers:
       cluster: ha-prometheus-poc
```
Where "ha-prometheus-poc" is the cluster label value we write?

**Comment by VineethReddy02** [comment] 2021-04-21 10:37
I am slightly confused here. So you are querying Prometheus with remote-read configured to Promscale and you are unable to see the data that is ingested Promscale with HA mode?

**Comment by aburkevics** [comment] 2021-04-21 10:45
Yes, Prometheus is configured with remote-write & remote-read to Promscale which has HA mode enabled.

And Grafana has the Prometheus data-source configured, which is where I see that remote-read doesn't work as expected after enabling HA mode in Promscale.

**Comment by VineethReddy02** [comment] 2021-04-21 11:11
Interesting, I haven't noticed this issue. So can you share an example query you are using? I will try to reproduce this on my side.

**Comment by aburkevics** [comment] 2021-04-21 11:52
I'm using EC2 (AWS) stats Grafana dashboard for testing this. This is a query for total ammount of memory for an instance:
`node_memory_MemTotal_bytes{instance=~"$node:$port",job=~"$job"}`

Should we be using `cluster` label in our queries when HA is enabled?

When I query metrics in Prometheus "Graph", I don't see that any metric would have `cluster` label. Specifically searching for it, returns no results. Example query I used for that:
`up{cluster="ha-prometheus-poc"} == 0`

**Comment by VineethReddy02** [comment] 2021-04-21 13:49
Do you mind performing the same query with Promscale? You can add Promscale as the Prometheus datasource in Grafana. 
btw the external Labels are attached to the samples that go out of Prometheus for example alertManager, remote-storage systems etc...

**Comment by aburkevics** [comment] 2021-04-22 07:19
Hello!
I can confirm that when Promscale is configured as target in the Grafana "Prometheus" data-source, then all the metrics are there.

**Comment by VineethReddy02** [comment] 2021-04-26 14:07
Hi @aburkevics 
We found out the issue, So Prometheus appends the external labels to remote-read requests. 

In every Prometheus query, the label sets `cluster=<clusterName>` & `__replica__=<replicaName>` are appended. In our new HA mode. we drop the `__replica__` labelSet while ingesting the data to dedupe the samples received from multiple Prometheus instances. 

Now when Prometheus remote-read requests the Promscale the queries are attached with `cluster` & `__replica__` label sets. The samples stored doesn't match with labelSet `__replica__` so the query returns empty data. 

So the immediate workaround is you can query from Prometheus by adding an additional label matcher `{__replica__=""}` or `{__replica__=~".*"}` to your existing PromQL queries. 

This issue will be fixed in our upcoming Promscale release which includes the new HA mode GA. 

Similar issue reported in Cortex: [here](https://github.com/cortexproject/cortex/issues/3714)
Discussion in upstream Prometheus about not to append external labels to remote-read endpoints: [here](https://github.com/prometheus/prometheus/issues/7992)

**Comment by aburkevics** [comment] 2021-04-28 10:12
Hello!
Great to hear that the cause has been found.
I tried this remote_read config and it still doesn't find the data on startup:
```
   - url: "http://promscale-connector:9201/read"
     read_recent: true
     required_matchers:
       __replica__: ""
```
So for now I assume I'll need to wait for the update in Promscale to use it in ha-mode?

**Comment by VineethReddy02** [comment] 2021-04-28 13:44
Hi!

`required_matchers:` are an optional list of equality matchers which have to be present in a selector to query the remote read endpoint.

So you should append this `{__replica__=""}` labelSet in your PromQL queries. That will give the results back from the Promscale HA setup.

**Comment by aburkevics** [comment] 2021-04-29 06:51
Hi!
I tested multiple configuration combinations with (and without) `required_matchers` and adding `{__replica__=""}` to queries in Grafana, but the result is the same - while Prometheus is up and running, all the active data can be queried. But once Prometheus is "purged" and brought up again from scratch, nothing is returned by remote_read.

Seems like we'll just wait for the next release where this feature is no more in experimental state.

**Closed** 2021-05-07 13:41 UTC
Labels: kind/bug
