### ISSUE TITLE
Memory issues when querying many data points

### ISSUE THREAD

**Issue by mauriciocirelli** [timescale/promscale#623] opened 2021-05-12 17:59 UTC
Dear,

I am in the process of migrating current Prometheus + Grafana setup to Prometheus + Promscale + Postgres + Grafana in order to have better performance, specially for long-term metrics. Unfortunately, I am having much worse performance in the new setup.

There is one metric that generates some thousands of data points everyday and my goal is to average them daily and present the results in a dashboard. Something pretty standard for Grafana.

1. At first, I configured Grafana to query Prometheus directly, but kept Promscale process running, so metrics were being written to the database. This query returns in 1.30min with 14K rows.

2. Then, I configured Grafana to query Promscale. This query times out (it actually crashes the server).

Looking at `top`, Promscale is using almost all RAM (90+%) and the system is doing a lot of swap. The system hangs and I have to kill promscale process to get it up again.

3. Finally, I configured Grafana to query Prometheus directly again, but turned off Promscale process. The same query returned 14K rows in 23 seconds.

I know debugging this kind of issue is hard but I am open for a screen share or something like that if it helps.

Thank you!

**Comment by Harkishen-Singh** [comment] 2021-05-18 12:56
Hey @mauriciocirelli thank you for reporting and I am sorry for the issue and delayed reply. Can you share your PromQL query that's causing the issue?

**Comment by mauriciocirelli** [comment] 2021-05-18 13:07
Hi!

Thank you for looking into this.

The query is very basic: avg_over_time(my_custom_metric{connectionType=~"4G"}[$__range])
This is a custom metric of ours to monitor connection quality of our devices. It returns points with their respective 4G signal strenght (4G networks in this case). $__range is Grafana's variable which represents current dashboard interval. In the case I reported the issue, it was last 24h.

**Comment by Harkishen-Singh** [comment] 2021-05-25 09:41
We are investigating this. The initial belief is that we are running out of db connection pools which may be the cause of slow down or timeout.

This can be a bug on our side. We will update here if on any event. Thank you for reporting!

**Comment by Harkishen-Singh** [comment] 2021-06-29 09:17
@cevian I think this issue is related to recent PRs on query improvements.

**Comment by VineethReddy02** [comment] 2022-08-17 17:28
closing this issue, we have made many performance improvements to Promscale. We expect this shouldn't be an issue anymore. 

If you still face an issue with the latest Promscale, please open a new issue. 

Thanks!

**Closed by VineethReddy02** 2022-08-17 17:28 UTC
Labels: Performance
