### ISSUE TITLE
Investigate the performance degradation in latest Promscale

### ISSUE THREAD

**Issue by peppercoffee** [timescale/promscale#1393] opened 2022-06-01 15:30 UTC
As described in [the thread on slack](https://iobeam.slack.com/archives/CP5EQ4V16/p1654083513653809)

**Comment by niksajakovljevic** [comment] 2022-06-17 11:11
The root cause was discovered - basically benchmark test had rules turned on accidentally which affected ingest performance. So we can close this one.

**Comment by Harkishen-Singh** [comment] 2022-07-25 06:32
Ingest performance with heavy recording rules is not affected after #1451 was merged. This was confirmed in the benchmarks discussed in the demo call.

**Closed by Harkishen-Singh** 2022-07-25 06:32 UTC
Labels: IIIP-1
